"""add regular_work_hours column

Revision ID: 0622ef29bd16
Revises: 23929aa3dfe0
Create Date: 2025-07-07 13:37:04.895651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0622ef29bd16'
down_revision = '23929aa3dfe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regular_work_hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_column('regular_work_hours')

    # ### end Alembic commands ###
