"""Add personal_signature to User model

Revision ID: 4510686a5aa4
Revises: 7f289bb1fb0f
Create Date: 2025-07-16 09:32:36.861077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4510686a5aa4'
down_revision = '7f289bb1fb0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_signature', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('personal_signature')

    # ### end Alembic commands ###
