"""add signature field to attendance

Revision ID: 7f289bb1fb0f
Revises: 0622ef29bd16
Create Date: 2025-07-10 10:24:04.281062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f289bb1fb0f'
down_revision = '0622ef29bd16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_column('signature')

    # ### end Alembic commands ###
