"""add approver signatures to attendance

Revision ID: add_approver_signatures
Revises: 7f289bb1fb0f
Create Date: 2025-01-27 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_approver_signatures'
down_revision = '7f289bb1fb0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_leader_signature', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manager_signature', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_column('manager_signature')
        batch_op.drop_column('team_leader_signature')

    # ### end Alembic commands ### 