"""Add leave_reason and attachments to LeaveRequest

Revision ID: add_leave_reason_attachments
Revises: a27061361835
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_leave_reason_attachments'
down_revision = 'a27061361835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('leave_reason', sa.Text(), nullable=False, server_default=''))
    op.add_column('leave_requests', sa.Column('attachments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_requests', 'attachments')
    op.drop_column('leave_requests', 'leave_reason')
    # ### end Alembic commands ###
