"""Add signer ID fields for team leader and manager

Revision ID: ea266e08c453
Revises: 4510686a5aa4
Create Date: 2025-07-16 15:17:06.331330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea266e08c453'
down_revision = '4510686a5aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_leader_signer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('manager_signer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_attendances_manager_signer_id', 'users', ['manager_signer_id'], ['id'])
        batch_op.create_foreign_key('fk_attendances_team_leader_signer_id', 'users', ['team_leader_signer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attendances_manager_signer_id', type_='foreignkey')
        batch_op.drop_constraint('fk_attendances_team_leader_signer_id', type_='foreignkey')
        batch_op.drop_column('manager_signer_id')
        batch_op.drop_column('team_leader_signer_id')

    # ### end Alembic commands ###
