"""Add overtime columns

Revision ID: fb505dc1b8ba
Revises: 
Create Date: 2025-06-16 11:12:16.977136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb505dc1b8ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overtime_before_22', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overtime_after_22', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('overtime_after_22')
        batch_op.drop_column('overtime_before_22')

    # ### end Alembic commands ###
